set dotenv-load
set shell := ["bash", "-cu"]

# Required env (in .env):
#   SANDBOX_NAME — sbx sandbox name (arbitrary; created if it doesn't exist)
#   SANDBOX_DIR  — absolute host path used as the sandbox's primary workspace.
#                  Per-project session dirs live at $SANDBOX_DIR/projects/, so any
#                  files generated by claude inside a session are visible on the host.
#                  MUST NOT be the same as the codebase directory.
# Optional:
#   PORT         — server port (default 3000)

CODE_DIR := justfile_directory()

default: up

# Ensure the sandbox exists, has its deps, and is running the server.
# Idempotent — safe to re-run.
up:
    @[ -n "${SANDBOX_NAME:-}" ] || { echo "error: SANDBOX_NAME is not set (configure in .env)" >&2; exit 1; }
    @[ -n "${SANDBOX_DIR:-}" ]  || { echo "error: SANDBOX_DIR is not set (configure in .env)"  >&2; exit 1; }
    @if [ "$SANDBOX_DIR" = "{{CODE_DIR}}" ]; then \
        echo "error: SANDBOX_DIR must not be the codebase dir ({{CODE_DIR}})." >&2; \
        echo "       Set it to a separate workspace path where generated files should live." >&2; \
        exit 1; \
    fi
    @mkdir -p "$SANDBOX_DIR"
    @if ! sbx ls 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$SANDBOX_NAME"; then \
        echo "creating sandbox '$SANDBOX_NAME' (workspace=$SANDBOX_DIR, code={{CODE_DIR}}:ro)..."; \
        sbx create --name "$SANDBOX_NAME" claude "$SANDBOX_DIR" "{{CODE_DIR}}:ro"; \
    else \
        echo "sandbox '$SANDBOX_NAME' already exists"; \
    fi
    @echo "ensuring sandbox deps (just/tmux/ttyd)..."
    @sbx exec "$SANDBOX_NAME" bash -lc 'missing=; for c in just tmux ttyd; do command -v $c >/dev/null || missing="$missing $c"; done; if [ -n "$missing" ]; then echo "installing:$missing"; while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do echo "  waiting for other apt process..."; sleep 3; done; sudo apt-get update -qq && sudo apt-get install -y -qq $missing; fi'
    # Background the sbx exec on the HOST (not -d in the sandbox) — sbx's auto-stop
    # counts host-side connected sessions, not processes inside the VM. `&` keeps the
    # session connected; `disown` detaches it from this shell so it survives `just up`.
    # Idempotent: skip the launch if a session is already alive.
    @if pgrep -f "sbx exec $SANDBOX_NAME" >/dev/null 2>&1; then \
        echo "server already running (host-side session present)"; \
    else \
        echo "starting server..."; \
        sbx exec "$SANDBOX_NAME" bash -lc "cd '{{CODE_DIR}}' && just _serve" > /tmp/sbx-serve.log 2>&1 & disown; \
    fi
    @if sbx ports "$SANDBOX_NAME" 2>/dev/null | grep -q ":${PORT}"; then \
        echo "port ${PORT} already published"; \
    else \
        sbx ports "$SANDBOX_NAME" --publish "${PORT}:${PORT}"; \
    fi
    @echo "→ http://127.0.0.1:${PORT}"
    @echo "  logs:  just logs"
    @echo "  stop:  just down"

# Clean shutdown: stop the in-sandbox server, drop the host-side connection
# (which lets sbx auto-stop the sandbox), and unpublish the dashboard port.
# Idempotent — safe to re-run.
down:
    @[ -n "${SANDBOX_NAME:-}" ] || { echo "error: SANDBOX_NAME is not set" >&2; exit 1; }
    @if sbx ls 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$SANDBOX_NAME"; then \
        echo "stopping server inside '$SANDBOX_NAME'..."; \
        sbx exec "$SANDBOX_NAME" bash -lc "fuser -k ${PORT}/tcp 2>/dev/null || true" >/dev/null 2>&1 || true; \
    fi
    @if pgrep -f "sbx exec $SANDBOX_NAME" >/dev/null 2>&1; then \
        echo "killing host-side sbx exec sessions for '$SANDBOX_NAME'..."; \
        pkill -f "sbx exec $SANDBOX_NAME" 2>/dev/null || true; \
        sleep 1; \
    fi
    @sbx ports "$SANDBOX_NAME" --unpublish "${PORT}:${PORT}" 2>/dev/null || true
    @echo "stopped."

# Stop everything, then start fresh.
restart: down up

# Tail the server log (host-side capture of the in-sandbox process).
logs:
    tail -f /tmp/sbx-serve.log

# Show running state at a glance.
status:
    @echo "host-side sbx exec processes:"
    @pgrep -af "sbx exec $SANDBOX_NAME" || echo "  (none)"
    @echo
    @echo "sandbox & published ports:"
    @sbx ls 2>/dev/null | grep -E "^SANDBOX|$SANDBOX_NAME" || echo "  (not found)"
    @sbx ports "$SANDBOX_NAME" 2>/dev/null || true

# Internal: start the server. Only safe inside the sandbox.
# main.py's _require_sandbox() guard refuses to start if SANDBOX_VM_ID is unset.
# Code dir is mounted read-only, so the venv lives in $HOME and bytecode is suppressed.
_serve:
    @mkdir -p $HOME/.cache/claude-sessions
    PYTHONDONTWRITEBYTECODE=1 UV_PROJECT_ENVIRONMENT=$HOME/.cache/claude-sessions/.venv uv run main.py
