set dotenv-load
set shell := ["bash", "-cu"]

# Required env (in .env):
#   SANDBOX_NAME — sbx sandbox name (arbitrary; created if it doesn't exist)
#   SANDBOX_DIR  — absolute host path used as the sandbox's primary workspace.
#                  Per-project session dirs live at $SANDBOX_DIR/projects/, so any
#                  files generated by claude inside a session are visible on the host.
#                  MUST NOT be the same as the codebase directory.
# Optional:
#   PORT         — dashboard port (default 3000)
#   HOST_PORT    — host-daemon port for dynamic port exposure (default 33001)
#   TAILSCALE    — when non-empty, `just up` calls `tailscale serve` for the
#                  dashboard + daemon, and the host daemon does the same for
#                  every user-exposed port. Lets you reach everything from
#                  your phone over the tailnet. Requires `tailscale` on the
#                  host and `tailscale up` already done.

CODE_DIR := justfile_directory()

default: up

# Ensure the sandbox exists, has its deps, and is running the server.
# Idempotent — safe to re-run.
up:
    @[ -n "${SANDBOX_NAME:-}" ] || { echo "error: SANDBOX_NAME is not set (configure in .env)" >&2; exit 1; }
    @[ -n "${SANDBOX_DIR:-}" ]  || { echo "error: SANDBOX_DIR is not set (configure in .env)"  >&2; exit 1; }
    @if [ "$SANDBOX_DIR" = "{{CODE_DIR}}" ]; then \
        echo "error: SANDBOX_DIR must not be the codebase dir ({{CODE_DIR}})." >&2; \
        echo "       Set it to a separate workspace path where generated files should live." >&2; \
        exit 1; \
    fi
    @mkdir -p "$SANDBOX_DIR"
    @if ! sbx ls 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$SANDBOX_NAME"; then \
        echo "creating sandbox '$SANDBOX_NAME' (workspace=$SANDBOX_DIR, code={{CODE_DIR}}:ro)..."; \
        sbx create --name "$SANDBOX_NAME" claude "$SANDBOX_DIR" "{{CODE_DIR}}:ro"; \
    else \
        echo "sandbox '$SANDBOX_NAME' already exists"; \
    fi
    @echo "ensuring sandbox deps (just/tmux/ttyd)..."
    @sbx exec "$SANDBOX_NAME" bash -lc 'missing=; for c in just tmux ttyd; do command -v $c >/dev/null || missing="$missing $c"; done; if [ -n "$missing" ]; then echo "installing:$missing"; while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do echo "  waiting for other apt process..."; sleep 3; done; sudo apt-get update -qq && sudo apt-get install -y -qq $missing; fi'
    # Background the sbx exec on the HOST (not -d in the sandbox) — sbx's auto-stop
    # counts host-side connected sessions, not processes inside the VM. `&` keeps the
    # session connected; `disown` detaches it from this shell so it survives `just up`.
    # Idempotent: skip the launch if a session is already alive.
    @if pgrep -f "sbx exec $SANDBOX_NAME" >/dev/null 2>&1; then \
        echo "server already running (host-side session present)"; \
    else \
        echo "starting server..."; \
        sbx exec "$SANDBOX_NAME" bash -lc "cd '{{CODE_DIR}}' && just _serve" > /tmp/sbx-serve.log 2>&1 & disown; \
    fi
    @if sbx ports "$SANDBOX_NAME" 2>/dev/null | grep -q ":${PORT}"; then \
        echo "port ${PORT} already published"; \
    else \
        sbx ports "$SANDBOX_NAME" --publish "${PORT}:${PORT}"; \
    fi
    # Host-side port daemon. Runs OUTSIDE the sandbox — it's the only thing
    # allowed to invoke `sbx ports`. The sandbox never talks to it; the
    # browser does, directly. See host_daemon.py for the security rationale.
    @if pgrep -f "host_daemon.py" >/dev/null 2>&1; then \
        echo "host daemon already running"; \
    else \
        echo "starting host daemon on 127.0.0.1:${HOST_PORT:-33001}..."; \
        uv run host_daemon.py > /tmp/host-daemon.log 2>&1 & disown; \
    fi
    # Tailscale opt-in: expose the dashboard and the host daemon on the
    # tailnet so the dashboard works from a phone. The host daemon takes care
    # of `tailscale serve` for individual user-exposed ports as they come and
    # go; the dashboard + daemon themselves are bootstrap-level so they live
    # here. Failures (binary missing, not logged in, etc.) are warnings only.
    @if [ -n "${TAILSCALE:-}" ]; then \
        if ! command -v tailscale >/dev/null 2>&1; then \
            echo "warning: TAILSCALE is set but 'tailscale' is not on PATH — skipping tailnet serve" >&2; \
        else \
            echo "tailscale: serving dashboard at http://<tailnet>:${PORT}..."; \
            tailscale serve --bg --http=${PORT} "http://127.0.0.1:${PORT}" 2>&1 || true; \
            echo "tailscale: serving host daemon at http://<tailnet>:${HOST_PORT:-33001}..."; \
            tailscale serve --bg --http=${HOST_PORT:-33001} "http://127.0.0.1:${HOST_PORT:-33001}" 2>&1 || true; \
            tsname=$(tailscale status --self --json 2>/dev/null | sed -n 's/.*"DNSName":[[:space:]]*"\([^"]*\)".*/\1/p' | head -1 | sed 's/\.$//'); \
            [ -n "$tsname" ] && echo "→ tailnet: http://${tsname}:${PORT}"; \
        fi; \
    fi
    @echo "→ http://127.0.0.1:${PORT}"
    @echo "  logs:  just logs        (sandbox server)"
    @echo "  logs:  just logs-host   (host daemon)"
    @echo "  stop:  just down"

# Clean shutdown: stop the in-sandbox server, drop the host-side connection
# (which lets sbx auto-stop the sandbox), and unpublish the dashboard port.
# Idempotent — safe to re-run.
down:
    @[ -n "${SANDBOX_NAME:-}" ] || { echo "error: SANDBOX_NAME is not set" >&2; exit 1; }
    # Stop the host daemon FIRST: its SIGTERM handler unpublishes every port
    # it owns. If we kill the sandbox before this runs, the unpublish calls
    # still succeed (sbx state is host-side) but we'd race with `down`.
    @if pgrep -f "host_daemon.py" >/dev/null 2>&1; then \
        echo "stopping host daemon (will unpublish managed ports)..."; \
        pkill -TERM -f "host_daemon.py" 2>/dev/null || true; \
        for i in 1 2 3 4 5; do \
            pgrep -f "host_daemon.py" >/dev/null 2>&1 || break; \
            sleep 0.3; \
        done; \
        pkill -KILL -f "host_daemon.py" 2>/dev/null || true; \
    fi
    @if sbx ls 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$SANDBOX_NAME"; then \
        echo "stopping server inside '$SANDBOX_NAME'..."; \
        sbx exec "$SANDBOX_NAME" bash -lc "fuser -k ${PORT}/tcp 2>/dev/null || true" >/dev/null 2>&1 || true; \
    fi
    @if pgrep -f "sbx exec $SANDBOX_NAME" >/dev/null 2>&1; then \
        echo "killing host-side sbx exec sessions for '$SANDBOX_NAME'..."; \
        pkill -f "sbx exec $SANDBOX_NAME" 2>/dev/null || true; \
        sleep 1; \
    fi
    @sbx ports "$SANDBOX_NAME" --unpublish "${PORT}:${PORT}" 2>/dev/null || true
    # Tear down dashboard + daemon tailnet serves we set up in `up`. The host
    # daemon already unserved every user-exposed port during its SIGTERM
    # handler above, so we only need to clean up the bootstrap ports here.
    @if [ -n "${TAILSCALE:-}" ] && command -v tailscale >/dev/null 2>&1; then \
        tailscale serve --http=${PORT} off 2>/dev/null || true; \
        tailscale serve --http=${HOST_PORT:-33001} off 2>/dev/null || true; \
    fi
    @echo "stopped."

# Stop everything, then start fresh.
restart: down up

# Tail the server log (host-side capture of the in-sandbox process).
logs:
    tail -f /tmp/sbx-serve.log

# Tail the host daemon log (the host-side port-management process).
logs-host:
    tail -f /tmp/host-daemon.log

# Show running state at a glance.
status:
    @echo "host-side sbx exec processes:"
    @pgrep -af "sbx exec $SANDBOX_NAME" || echo "  (none)"
    @echo
    @echo "host daemon:"
    @pgrep -af "host_daemon.py" || echo "  (not running)"
    @echo
    @echo "sandbox & published ports:"
    @sbx ls 2>/dev/null | grep -E "^SANDBOX|$SANDBOX_NAME" || echo "  (not found)"
    @sbx ports "$SANDBOX_NAME" 2>/dev/null || true

# Internal: start the server. Only safe inside the sandbox.
# main.py's _require_sandbox() guard refuses to start if SANDBOX_VM_ID is unset.
# Code dir is mounted read-only, so the venv lives in $HOME and bytecode is suppressed.
_serve:
    @mkdir -p $HOME/.cache/claude-sessions
    PYTHONDONTWRITEBYTECODE=1 UV_PROJECT_ENVIRONMENT=$HOME/.cache/claude-sessions/.venv uv run main.py
